### ISSUE TITLE
提示错误报告

### ISSUE THREAD

**Issue by lvhailong** [Young-Lord/qq-win-db-key#5]
![截屏2023-07-21 下午7 55 41](https://github.com/Young-Lord/qq-win-db-key/assets/9078308/2dd2cdb7-5033-4159-a133-e0616b22cff0)
测试了QQ9.7.3.28946和QQ9.7.6.28997都不行，运行main.py或hook.py后都会弹出错误报告并退出qq进程。

**Comment by Young-Lord** [comment]
QQProtect关了吗？重启试过吗？

**Comment by lvhailong** [comment]
> QQProtect关了吗？重启试过吗？

尝试在启动QQ后登陆前从进程里结束了QQ安全盾进程也不管用。重启也无效，依然会弹出那个窗口。另外，这是我命令行里的记录信息：
```
Microsoft Windows [版本 10.0.21301.1000]
(c) 2020 Microsoft Corporation. 保留所有权利。

C:\Users\lvhailong>cd C:\Users\lvhailong\Desktop\qq-win-db-key-master


C:\Users\lvhailong\Desktop\qq-win-db-key-master>python main.py
QQ pid is: 5024
Traceback (most recent call last):
  File "C:\Users\lvhailong\Desktop\qq-win-db-key-master\main.py", line 178, in <module>
    session = frida.get_local_device().attach(QQ_PID)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvhailong\AppData\Local\Programs\Python\Python311\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvhailong\AppData\Local\Programs\Python\Python311\Lib\site-packages\frida\core.py", line 1010, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.ProcessNotRespondingError: process with pid 5024 either refused to load frida-agent, or terminated during injection

C:\Users\lvhailong\Desktop\qq-win-db-key-master>
```

**Comment by Young-Lord** [comment]
> > QQProtect关了吗？重启试过吗？
> 
> 尝试在启动QQ后登陆前从进程里结束了QQ安全盾进程也不管用。重启也无效，依然会弹出那个窗口。另外，这是我命令行里的记录信息：

能否试试用README中的知乎链接永久关闭QQProtect？

**Comment by lvhailong** [comment]
> > > QQProtect关了吗？重启试过吗？
> > 
> > 
> > 尝试在启动QQ后登陆前从进程里结束了QQ安全盾进程也不管用。重启也无效，依然会弹出那个窗口。另外，这是我命令行里的记录信息：
> 
> 能否试试用README中的知乎链接永久关闭QQProtect？

我按照知乎里的方法删除了QQProtect但依旧是同样的错误弹窗

**Comment by Young-Lord** [comment]
emm 那就不太清楚了，抱歉帮不上忙

**Comment by kingsznhone** [comment]
相关技术已经基本成熟，请查阅文档

https://qqbackup.github.io/QQDecrypt/
